### ISSUE TITLE
 Missing closing back-ticks on jldoctest causes corrupt documentation but does not fail checks

### ISSUE THREAD

**Issue by LilithHafner** [JuliaDocs/MarkdownAST.jl#28]
I forgot some closing backticks in a jldoctest block (fixed here https://github.com/LilithHafner/AliasTables.jl/pull/29) which should, in order of preference

1) Fail the documentation build
2) Render okay
3) Break that docstring's rendering
4) Break that docstring's rendering and some subsequent content
5) Break the whole documentation page but still show up as a pass

Right now we're at a 3 or 4 here: https://aliastables.lilithhafner.com/v1.0.0/#AliasTables.probabilities

Moved from https://github.com/LuxDL/DocumenterVitepress.jl/issues/116

**Comment by mortenpi** [comment]
Closing in favor of https://github.com/JuliaDocs/Documenter.jl/issues/2059#issue-1610450484

The best you can do is a linter -- any sequence of bytes is valid Markdown, so a parser is expected to parse it without complaining:

```
julia> m = md"""
       Foo

       ```jldoctest
       bar

       Baz
       """
  Foo

  ```jldoctest bar

  Baz

julia> m.content
3-element Vector{Any}:
 Markdown.Paragraph(Any["Foo"])
 Markdown.Paragraph(Any["```jldoctest bar"])
 Markdown.Paragraph(Any["Baz"])
```

Out of scope for MarkdownAST though -- it doesn't know the source code, so it has no way to know if the AST is intentional or not.
